global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sensor_discovery'
    static_configs:
    - targets: ['json-exporter:9103']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
